// <auto-generated />
using System;
using CommonAuthApp.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CommonAuthApp.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250920192407_schoolSetup")]
    partial class schoolSetup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CommonAuthApp.API.Models.ProductModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<string>("ProductName")
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("CommonAuthApp.API.Models.RefreshTokenModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("CommonAuthApp.API.Models.RoleModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("RoleName")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("CommonAuthApp.API.Models.SchoolMenu", b =>
                {
                    b.Property<int>("MenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MenuId"));

                    b.Property<int>("CreateBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MenuIsActive")
                        .HasColumnType("integer");

                    b.Property<string>("MenuName")
                        .HasColumnType("text");

                    b.Property<int>("MenuSerial")
                        .HasColumnType("integer");

                    b.Property<string>("MenuUrlPath")
                        .HasColumnType("text");

                    b.HasKey("MenuId");

                    b.ToTable("SchoolMenus");
                });

            modelBuilder.Entity("CommonAuthApp.API.Models.SchoolModel", b =>
                {
                    b.Property<int>("SchoolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SchoolId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("SchoolAddress")
                        .HasColumnType("text");

                    b.Property<string>("SchoolArea")
                        .HasColumnType("text");

                    b.Property<string>("SchoolCode")
                        .HasColumnType("text");

                    b.Property<string>("SchoolConactPersonMobileNo")
                        .HasColumnType("text");

                    b.Property<string>("SchoolContactPerson")
                        .HasColumnType("text");

                    b.Property<string>("SchoolContactPersonPosition")
                        .HasColumnType("text");

                    b.Property<string>("SchoolDistrict")
                        .HasColumnType("text");

                    b.Property<string>("SchoolDivision")
                        .HasColumnType("text");

                    b.Property<string>("SchoolEiin")
                        .HasColumnType("text");

                    b.Property<string>("SchoolLogoPath")
                        .HasColumnType("text");

                    b.Property<string>("SchoolName")
                        .HasColumnType("text");

                    b.Property<string>("SchoolPostalCode")
                        .HasColumnType("text");

                    b.Property<int>("SchoolStatus")
                        .HasColumnType("integer");

                    b.Property<string>("SchoolThana")
                        .HasColumnType("text");

                    b.Property<string>("SchoolType")
                        .HasColumnType("text");

                    b.HasKey("SchoolId");

                    b.ToTable("Schools");
                });

            modelBuilder.Entity("CommonAuthApp.API.Models.SchoolSystemDetails", b =>
                {
                    b.Property<int>("SystemDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SystemDetailsId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("SchoolDBConnectionString")
                        .HasColumnType("text");

                    b.Property<string>("SchoolDBName")
                        .HasColumnType("text");

                    b.Property<string>("SchoolDBPass")
                        .HasColumnType("text");

                    b.Property<int>("SchoolDBPort")
                        .HasColumnType("integer");

                    b.Property<string>("SchoolDBServer")
                        .HasColumnType("text");

                    b.Property<string>("SchoolDBSystemName")
                        .HasColumnType("text");

                    b.Property<string>("SchoolDBUsername")
                        .HasColumnType("text");

                    b.Property<int>("SchoolId")
                        .HasColumnType("integer");

                    b.Property<string>("SchoolServerIP")
                        .HasColumnType("text");

                    b.Property<int>("SchoolServerPort")
                        .HasColumnType("integer");

                    b.HasKey("SystemDetailsId");

                    b.ToTable("SchoolSystemDetails");
                });

            modelBuilder.Entity("CommonAuthApp.API.Models.UserModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CommonAuthApp.API.Models.UserRoleModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("RoleID")
                        .HasColumnType("integer");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("RoleID");

                    b.HasIndex("UserID");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("CommonAuthApp.API.Models.RefreshTokenModel", b =>
                {
                    b.HasOne("CommonAuthApp.API.Models.UserModel", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CommonAuthApp.API.Models.UserRoleModel", b =>
                {
                    b.HasOne("CommonAuthApp.API.Models.RoleModel", "Role")
                        .WithMany()
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CommonAuthApp.API.Models.UserModel", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CommonAuthApp.API.Models.UserModel", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
